### ISSUE TITLE
Google drive link does not work

### ISSUE THREAD

**Issue by jnirschl** [jarek-pawlowski/microbial-dataset-generation#2]
I tried to access the data via the Google drive link, but it says the file does not exist.

![image](https://user-images.githubusercontent.com/9021630/194203784-6ca5eb2c-698a-4f9a-852a-d6ec54a01396.png)

**Comment by jarek-pawlowski** [comment]
Thank you, we just removed the unnecessary link to google-drive, the first link is already working.
