### ISSUE TITLE
Invalid zip file using data.neurosys.com link

### ISSUE THREAD

**Issue by jnirschl** [jarek-pawlowski/microbial-dataset-generation#3]
I try to extract the archive but get an error that the zip is corrupt or not a valid zip file.
https://data.neurosys.com:4443/agar-public/microbial_dataset_generation.zip

Filename: microbial_dataset_generation.zip (File size: 1.3kb)
MD5 hash of downloaded file: a7f7c574d2f36240713b9f14cd4642d7

**Comment by jarek-pawlowski** [comment]
Thank you for noticing the problem, we fixed the broken link, and now the zip file is downloadable.
